apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rastir

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: prometheus-rules
    files:
      - rules/rastir-sre-rules.yml
      - rules/alerts.yaml

generatorOptions:
  disableNameSuffixHash: true
