apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: rastir
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: rastir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
