title: Rastir
description: LLM & Agent Observability Library for Python
remote_theme: just-the-docs/just-the-docs@v0.10.0
plugins:
  - jekyll-remote-theme

baseurl: /rastir
url: https://skamalj.github.io

color_scheme: dark

# Search
search_enabled: true
search.button: true

# Aux links (top-right)
aux_links:
  "GitHub":
    - "https://github.com/skamalj/rastir"
aux_links_new_tab: true

# Footer
footer_content: "Rastir — LLM & Agent Observability Library"

markdown: kramdown
highlighter: rouge
