server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Inject runtime env vars into a JS config file
    location /config.js {
        default_type application/javascript;
        return 200 "window.RASTIR_API_URL='${API_URL}';";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
